### ISSUE TITLE
Ícone ficando atrás de outra div

### ISSUE THREAD

**Issue by leandrodavimg** [rafaelbotazini/floating-whatsapp#1]
O ícone está ficando atrás de outra div, acredito que o z-índex resolveria.

**Comment by rafaelbotazini** [comment]
Foi adicionada possibilidade de customizar a propriedade `z-index`. 

Recurso disponível a partir da versão [1.1.0](https://github.com/rafaelbotazini/floating-whatsapp/releases/tag/v1.1.0).

**Comment by rafaelbotazini** [comment]
### Resolved (see pull request #3)
