### ISSUE TITLE
How to open Fake Chat Window programmatically?

### ISSUE THREAD

**Issue by hmaesta** [rafaelbotazini/floating-whatsapp#10]
Hello, Rafael.
Thank you the nice plugin.

How can I open the _Fake Chat Window_ programmatically, like an API call?

For example:
```js
$('.trigger').on('click', function () {
   $floatingWhatsApp.openChat();
});

```

Thanks! 👋

**Comment by rafaelbotazini** [comment]
Hey, Hugo.

The plugin doesn't have this feature yet.

I'm kinda short of time to implement this feature by now, but I will gladly accept a pull request if you or anyone else are willing to try and implement it.

You can also show the window by adding the class `.active` to the popup element:

```js
$('.trigger').on('click', function () {
   $('.floating-wpp-popup').addClass('active');
});
```
