### ISSUE TITLE
On desktop browser it goes to launch WhatsApp web, instead of using the app already installed

### ISSUE THREAD

**Issue by prearisto** [rafaelbotazini/floating-whatsapp#13]
The choosing api or web subdomain is not needed.
Should be always api.whatsapp.com

**Comment by rafaelbotazini** [comment]
When I wrote this plugin, Firefox couldn't open api.whatsapp.com links for some reason. This is why I made it that way. 

Seems like they fixed it now. I am going to change it then.

Thanks for the heads up!

**Comment by martinsSmith** [comment]
have u fixed it??
