### ISSUE TITLE
fake chat window

### ISSUE THREAD

**Issue by block0xhash** [rafaelbotazini/floating-whatsapp#16]
Good day ,

Is the a way to always have the fake chat window on top.

I have a twitter bootstrap card on my page and when I resize the the webpage the chat window is going behind the card item.

![image](https://user-images.githubusercontent.com/16897613/93543455-e8b90080-f95b-11ea-9570-9176fad35ae4.png)

Thanks
Bothwell

**Comment by rafaelbotazini** [comment]
Have you tried to set the `zIndex` option?

You should set this value higher than the card css `z-index` value.

**Comment by block0xhash** [comment]
thanks it works!

![image](https://user-images.githubusercontent.com/16897613/93691956-fbaf0a80-faec-11ea-9168-41d5a7397960.png)
