### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by wesionaire** [rafaelbotazini/floating-whatsapp#8]
Hi @rafaelbotazini ,

we really like your WhatApp jQuery plugin.

What license does it use? MIT, GPL, ...?

Regards

**Comment by rafaelbotazini** [comment]
Hello, and thank you so much!

This repository uses the MIT license.

License file was added at commit [3d18b26](https://github.com/rafaelbotazini/floating-whatsapp/commit/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68).
